ARG BUILD_IMAGE=ubuntu:24.04
FROM ubuntu:24.04 AS bcc

USER root

WORKDIR /dependencies

# bcc dependencies
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y \
    && apt install -y \
    zip \
    bison \
    build-essential \
    cmake \
    flex \
    git \
    libedit-dev \
    libllvm18 \
    llvm-18-dev \
    libcap2-bin \
    libclang-18-dev \
    python3 \
    python3-pip \
    zlib1g-dev \
    libelf-dev \
    libfl-dev \
    python3-setuptools \
    liblzma-dev \
    libdebuginfod-dev \
    arping \
    netperf \
    iperf \
    libpolly-18-dev \
    && apt clean

RUN git clone  --depth 1 --branch v0.31.0 https://github.com/iovisor/bcc.git
WORKDIR /dependencies/bcc/build
RUN cmake -DPYTHON_CMD=python3 ..
RUN make -j4
RUN make install

# Install OSQuery
RUN apt update -y \
  && apt install -y \
  curl \
  && apt clean
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL  https://pkg.osquery.io/deb/pubkey.gpg | gpg --dearmor -o /etc/apt/keyrings/osquery.gpg
RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/osquery.gpg] https://pkg.osquery.io/deb deb main" \
  | tee /etc/apt/sources.list.d/osquery.list > /dev/null
RUN apt update -y \
    && apt install -y \
    osquery \
    && apt clean
RUN cp /opt/osquery/share/osquery/osquery.example.conf /etc/osquery/osquery.conf

# benchmark dependencies
RUN apt update -y \
    && apt install -y \
    git \
    fakeroot \
    build-essential \
    libncurses-dev \
    xz-utils \
    libssl-dev \
    bc \
    flex \
    libelf-dev \
    bison \
    && apt clean

# Base development image
FROM ${BUILD_IMAGE} AS dev

ARG IS_CI=true

RUN apt update -y \
  &&  apt install -y \
  vim \
  pkg-config \
  shfmt \
  && apt clean

RUN if [ "${IS_CI}" != "true" ] ; then \
  apt update -y \
    &&  apt install -y \
    vim \
    zsh \
    && apt clean; fi

ARG UNAME
ARG UID
ARG GID

# May be required for Ubuntu:24.04 images that come with uid 1000
RUN deluser --remove-home ubuntu
RUN if [ "${UNAME}" != "root" ] ; then groupadd -g ${GID} ${UNAME} \
      &&  useradd -ms /bin/bash  -u "${UID}" -g "${GID}" ${UNAME}; fi

RUN mkdir -p /home/${UNAME} \
      && chown ${UNAME}:${UNAME} /home/${UNAME}

USER ${UNAME}

ARG SRC_DIR=/KernMLOps
RUN echo "export SRC_DIR=${SRC_DIR}" >> /home/${UNAME}/.profile
RUN mkdir -p /home/${UNAME}/.local
RUN echo "export PATH=$PATH:/home/pkenney/.local/bin" >> /home/${UNAME}/.profile

WORKDIR /home/${UNAME}
COPY --chown=${UNAME} requirements.txt /home/${UNAME}/requirements.txt
RUN pip install \
  --break-system-packages \
  --user --no-warn-script-location \
  -r /home/${UNAME}/requirements.txt

# Give python capabilities to load eBPF programs
USER root
RUN setcap CAP_SYS_ADMIN,CAP_DAC_READ_SEARCH,CAP_SYS_RESOURCE,CAP_NET_ADMIN,CAP_SETPCAP,CAP_PERFMON=+eip /usr/bin/python3.12
RUN ln -s /usr/bin/python3.12 /usr/bin/python

USER ${UNAME}
WORKDIR ${SRC_DIR}

LABEL creator="${UNAME}"
LABEL project="KernMLOps"
